<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\Skvia.BaseTemplate.ServiceDefaults\Skvia.BaseTemplate.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Skvia.BaseTemplate.Application\Skvia.BaseTemplate.Application.csproj" />
    <ProjectReference Include="..\Skvia.BaseTemplate.Infrastructure\Skvia.BaseTemplate.Infrastructure.csproj" />
  </ItemGroup>

</Project>

